package graphics

var DRM_MODE_CONNECTOR_Unknown uint32 = 0
var DRM_MODE_CONNECTOR_VGA uint32 = 1
var DRM_MODE_CONNECTOR_DVII uint32 = 2
var DRM_MODE_CONNECTOR_DVID uint32 = 3
var DRM_MODE_CONNECTOR_DVIA uint32 = 4
var DRM_MODE_CONNECTOR_Composite uint32 = 5
var DRM_MODE_CONNECTOR_SVIDEO uint32 = 6
var DRM_MODE_CONNECTOR_LVDS uint32 = 7
var DRM_MODE_CONNECTOR_Component uint32 = 8
var DRM_MODE_CONNECTOR_9PinDIN uint32 = 9
var DRM_MODE_CONNECTOR_DisplayPort uint32 = 10
var DRM_MODE_CONNECTOR_HDMIA uint32 = 11
var DRM_MODE_CONNECTOR_HDMIB uint32 = 12
var DRM_MODE_CONNECTOR_TV uint32 = 13
var DRM_MODE_CONNECTOR_eDP uint32 = 14
var DRM_MODE_CONNECTOR_VIRTUAL uint32 = 15
var DRM_MODE_CONNECTOR_DSI uint32 = 16
var DRM_MODE_CONNECTOR_DPI uint32 = 17
var DRM_MODE_CONNECTOR_WRITEBACK uint32 = 18
var DRM_MODE_CONNECTOR_SPI uint32 = 19
var DRM_MODE_CONNECTOR_USB uint32 = 20
