package graphics

// xf86drmMode.h

var DRM_MODE_SUBPIXEL_UNKNOWN uint32 = 1
var DRM_MODE_SUBPIXEL_HORIZONTAL_RGB uint32 = 2
var DRM_MODE_SUBPIXEL_HORIZONTAL_BGR uint32 = 3
var DRM_MODE_SUBPIXEL_VERTICAL_RGB uint32 = 4
var DRM_MODE_SUBPIXEL_VERTICAL_BGR uint32 = 5
var DRM_MODE_SUBPIXEL_NONE uint32 = 6
